import heroCoffee from '@/assets/hero-coffee.jpg';
import espressoImg from '@/assets/espresso.jpg';
import cappuccinoImg from '@/assets/cappuccino.jpg';
import icedCoffee from '@/assets/iced-coffee.jpg';
import croissant from '@/assets/croissant.jpg';

// New assets
import sandwichImg from '@/assets/menu/sandwich.png';
import waffleImg from '@/assets/menu/waffle.png';
import frappeImg from '@/assets/menu/frappe.png';
import mojitoImg from '@/assets/menu/mojito.png';
import addonsImg from '@/assets/menu/addons.png';

import { MenuItem } from './store';

export const menuItems: MenuItem[] = [
  // --- SAVOURY BUDS ---
  {
    id: 's1',
    name: 'Coleslaw Sandwich',
    price: 69,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Fresh coleslaw with creamy dressing in toasted bread',
    isAvailable: true,
  },
  {
    id: 's2',
    name: 'Veg Grilled Sandwich',
    price: 99,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Classic grilled sandwich with fresh seasonal vegetables',
    isAvailable: true,
  },
  {
    id: 's3',
    name: 'Cheese Corn Sandwich',
    price: 99,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Golden corn and melted cheese grilled to perfection',
    isAvailable: true,
  },
  {
    id: 's4',
    name: 'Tandoori Paneer Sandwich',
    price: 99,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Spiced tandoori paneer with mint chutney in grilled bread',
    isAvailable: true,
  },
  {
    id: 's5',
    name: 'Veg Salsa Wrap',
    price: 109,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Zesty salsa and fresh veggies wrapped in a soft tortilla',
    isAvailable: true,
  },
  {
    id: 's6',
    name: 'Paneer Masala Wrap',
    price: 139,
    category: 'savoury-buds',
    image: sandwichImg,
    description: 'Spiced paneer masala with crunchy veggies in a wrap',
    isAvailable: true,
  },

  // --- DESSERTS & WAFFLES ---
  {
    id: 'd1',
    name: 'Milky Silky Waffle',
    price: 89,
    category: 'dessert',
    image: waffleImg,
    description: 'Soft waffle with white chocolate drizzle and milk cream',
    isAvailable: true,
  },
  {
    id: 'd2',
    name: 'Dark Moon Waffle',
    price: 89,
    category: 'dessert',
    image: waffleImg,
    description: 'Rich dark chocolate waffle for the true cocoa lover',
    isAvailable: true,
  },
  {
    id: 'd3',
    name: 'Nutella Waffle',
    price: 149,
    category: 'dessert',
    image: waffleImg,
    description: 'Double layer of Nutella on a warm, crispy waffle',
    isAvailable: true,
  },
  {
    id: 'd4',
    name: 'Tripple Chocolate Waffle',
    price: 129,
    category: 'dessert',
    image: waffleImg,
    description: 'Belgian, milk, and dark chocolate combined',
    isAvailable: true,
  },
  {
    id: 'd5',
    name: 'Chocolate Brownie',
    price: 49,
    category: 'dessert',
    image: waffleImg,
    description: 'Fudgy, gooey chocolate brownie',
    isAvailable: true,
  },
  {
    id: 'd6',
    name: 'Choco Chip Cookies',
    price: 19,
    category: 'dessert',
    image: croissant,
    description: 'Classic crunchy cookie with chocolate chips',
    isAvailable: true,
  },
  {
    id: 'd7',
    name: 'Oats And Nuts Cookies',
    price: 19,
    category: 'dessert',
    image: croissant,
    description: 'Healthy and crunchy cookies with oats and premium nuts',
    isAvailable: true,
  },

  // --- COFFEE & HOT CHOCOLATE ---
  {
    id: 'c1',
    name: 'Espresso',
    price: 39,
    category: 'coffee',
    image: espressoImg,
    description: 'Pure and intense coffee classic',
    isAvailable: true,
  },
  {
    id: 'c2',
    name: 'Americano',
    price: 49,
    category: 'coffee',
    image: heroCoffee,
    description: 'Espresso shots topped with hot water',
    isAvailable: true,
  },
  {
    id: 'c3',
    name: 'Cappuccino',
    price: 59,
    category: 'coffee',
    image: cappuccinoImg,
    description: 'Perfectly balanced espresso, steamed milk, and foam',
    isAvailable: true,
  },
  {
    id: 'c4',
    name: 'Latte',
    price: 69,
    category: 'coffee',
    image: heroCoffee,
    description: 'Smooth espresso with plenty of steamed milk',
    isAvailable: true,
  },
  {
    id: 'c5',
    name: 'Mocha',
    price: 79,
    category: 'coffee',
    image: heroCoffee,
    description: 'Espresso with rich chocolate and steamed milk',
    isAvailable: true,
  },
  {
    id: 'c6',
    name: 'Hot Chocolate',
    price: 99,
    category: 'coffee',
    image: heroCoffee,
    description: 'Rich, creamy chocolate melted into warm milk',
    isAvailable: true,
  },

  // --- FRAPPÉS ---
  {
    id: 'f1',
    name: 'Coffee Frappé',
    price: 119,
    category: 'frappe',
    image: frappeImg,
    description: 'Classic blended coffee with ice and milk (480ml available: ₹169)',
    isAvailable: true,
  },
  {
    id: 'f2',
    name: 'Caramel Choco Frappé',
    price: 139,
    category: 'frappe',
    image: frappeImg,
    description: 'Blended coffee with caramel and chocolate (480ml available: ₹189)',
    isAvailable: true,
  },
  {
    id: 'f3',
    name: 'Blueberry Cheesecake Frappé',
    price: 139,
    category: 'frappe',
    image: frappeImg,
    description: 'Creamy cheesecake flavor with blueberry bits',
    isAvailable: true,
  },
  {
    id: 'f4',
    name: 'Lotus Biscoff Frappé',
    price: 239,
    category: 'frappe',
    image: frappeImg,
    description: 'Luxurious blend with original Lotus Biscoff speculoos',
    isAvailable: true,
  },

  // --- ICED BEVERAGES ---
  {
    id: 'i1',
    name: 'Iced Americano',
    price: 69,
    category: 'iced-beverages',
    image: icedCoffee,
    description: 'Chilled espresso over ice',
    isAvailable: true,
  },
  {
    id: 'i2',
    name: 'Mint Mojito',
    price: 89,
    category: 'iced-beverages',
    image: mojitoImg,
    description: 'Refreshing mint and lime sparkler',
    isAvailable: true,
  },
  {
    id: 'i3',
    name: 'Kiwi Mojito',
    price: 89,
    category: 'iced-beverages',
    image: mojitoImg,
    description: 'Tropical kiwi infused refreshing mojito',
    isAvailable: true,
  },
  {
    id: 'i4',
    name: 'Lemon Ice Tea',
    price: 79,
    category: 'iced-beverages',
    image: mojitoImg,
    description: 'Classic chilled tea with a zesty lemon twist',
    isAvailable: true,
  },

  // --- SPECIALS ---
  {
    id: 'sp1',
    name: 'Affogato',
    price: 149,
    category: 'coffee',
    image: cappuccinoImg,
    description: 'Vanilla ice cream topped with a hot shot of espresso',
    isAvailable: true,
  },
  // --- ADD-ONS ---
  {
    id: 'a1',
    name: 'Espresso Single Shot',
    price: 29,
    category: 'addons',
    image: addonsImg,
    description: 'Extra shot of our signature espresso',
    isAvailable: true,
  },
  {
    id: 'a2',
    name: 'Whipped Cream',
    price: 29,
    category: 'addons',
    image: addonsImg,
    description: 'Fluffy, sweet whipped cream topping',
    isAvailable: true,
  },
  {
    id: 'a3',
    name: 'Chocolate / Flavour',
    price: 19,
    category: 'addons',
    image: addonsImg,
    description: 'Extra drizzle or flavored syrup',
    isAvailable: true,
  },
  {
    id: 'a4',
    name: 'Ice Cream Scoop',
    price: 29,
    category: 'addons',
    image: addonsImg,
    description: 'Creamy vanilla ice cream scoop',
    isAvailable: true,
  },
];
